version: '3'
services:
  postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_USER: skynet
      POSTGRES_PASSWORD: skynet
    ports:
      - 5432:5432
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      # To keep data between restarts uncomment the next line
      # - ./postgres-data:/var/lib/postgresql/data

  camunda:
    image: camunda:local-build
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/camunda
      SPRING_DATASOURCE_USERNAME: skynet
      SPRING_DATASOURCE_PASSWORD: skynet
      WAIT_FOR: postgres:5432
      CAMUNDA_BPM_ADMIN-USER_ID: admin
      CAMUNDA_BPM_ADMIN-USER_PASSWORD: admin
      LOGGING_LEVEL_ROOT: INFO
      skynet_HTTP_READTIMEOUTSECS: 31
      skynet_HTTP_CONNECTIONTIMEOUTSECS: 12
      skynet_HTTP_HEADERS_TEST: ABC
      skynet_HTTP_URLS_MOCK: http://mock-service:9999
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 1024M
    volumes:
      - ../../src/test/resources/:/camunda/configuration/resources/

  mock-service:
    image: rodolpheche/wiremock
    ports:
      - 9999:9999
    volumes:
      - ./mock-services:/home/wiremock/mappings
    command: --verbose --global-response-templating --local-response-templating --port 9999
